export enum MASSAGE_NOTIFICATION {
  SIGN_IN_SUCCESS = "Logged in successfully",
  SIGN_IN_FAIL = "Login failed",
  SIGN_UP_SUCCESS = "Successfully registered account",
  SIGN_UP_FAIL = "Account registration failed",
  REMOVE_FRIEND_SUCCESS = "Remove friend successfully",
  REMOVE_FRIEND_ERROR = "Failed to remove friend",
  ADD_FRIEND_SUCCESS = "Friends added successfully",
  ADD_FRIEND_FAIL = "Adding friends failed",
  SEND_FRIEND_REQUEST_SUCCESS = "Sent friend request successfully",
  SEND_FRIEND_REQUEST_FAIL = "failed to send friend request",
  REVOKE_FRIEND_REQUEST_SUCCESS = "Successfully revoked friend request",
  REVOKE_FRIEND_REQUEST_FAIL = "Revoke failed friend requests",
  UPDATE_SUCCESSFUL = "Update successful",
  UPDATE_FAILED = "update failed",
}
